// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CameraAPI;

namespace CameraAPI.Models
{
    public partial class OrderDetail
    {
        public int? OrderId { get; set; }
        public int? CameraId { get; set; }
        public decimal? Quantity { get; set; }
        public string Status { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool? IsDelete { get; set; }
        public Camera Camera { get; set; }
    }
}